//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gymAppV2.Entrenadores
{


    public partial class Entrenadores
    {

        protected global::System.Web.UI.WebControls.Literal litTitulo;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeCount;
        protected global::System.Web.UI.WebControls.Literal litStatTotal;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Literal litStatActivos;
        protected global::System.Web.UI.WebControls.Label lblActivos;
        protected global::System.Web.UI.WebControls.Literal litStatConAlumnos;
        protected global::System.Web.UI.WebControls.Label lblConAlumnos;
        protected global::System.Web.UI.WebControls.Literal litStatSinUsuario;
        protected global::System.Web.UI.WebControls.Label lblSinUsuario;
        protected global::System.Web.UI.WebControls.Literal litListaTitulo;
        protected global::System.Web.UI.WebControls.GridView gvEntrenadores;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl footerText;
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCrear;
        protected global::System.Web.UI.WebControls.Literal litBtnCrear;
        protected global::System.Web.UI.HtmlControls.HtmlButton btnModificar;
        protected global::System.Web.UI.WebControls.Literal litBtnModificar;
        protected global::System.Web.UI.HtmlControls.HtmlButton btnEliminar;
        protected global::System.Web.UI.WebControls.Literal litBtnEliminar;
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCancelar;
        protected global::System.Web.UI.WebControls.Literal litBtnCancelar;

        /// <summary>
        /// pnlForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;

        protected global::System.Web.UI.WebControls.Label lblFormTitle;

        /// <summary>
        /// btnCloseForm control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCloseForm;

        protected global::System.Web.UI.WebControls.TextBox txtDNI;
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;
        protected global::System.Web.UI.WebControls.TextBox txtApellido;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.TextBox txtFechaNacimiento;
        protected global::System.Web.UI.WebControls.CheckBox chkActivo;

        /// <summary>
        /// btnGuardar control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnGuardar;

        /// <summary>
        /// btnCancelarForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCancelarForm;
        protected global::System.Web.UI.WebControls.Literal litBtnGuardar;

        /// <summary>
        /// pnlConfirmarEliminar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlConfirmarEliminar;

        protected global::System.Web.UI.WebControls.Literal litConfirmarTitulo;

        /// <summary>
        /// btnCloseConfirm control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCloseConfirm;

        protected global::System.Web.UI.WebControls.Literal litConfirmarMsg;
        protected global::System.Web.UI.WebControls.Literal litConfirmarAviso;
        protected global::System.Web.UI.WebControls.Label lblEntrenadorAEliminar;
        protected global::System.Web.UI.WebControls.HiddenField hdnDniAEliminar;

        /// <summary>
        /// btnCancelarEliminar control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCancelarEliminar;
        protected global::System.Web.UI.WebControls.Literal litBtnCancelarEliminar;

        /// <summary>
        /// btnConfirmarEliminar control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnConfirmarEliminar;
        protected global::System.Web.UI.WebControls.Literal litBtnConfirmarEliminar;
    }
}
