//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gymAppV2.Entrenadores
{
    public partial class Entrenadores
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeCount;

        protected global::System.Web.UI.WebControls.Label lblTotal;

        protected global::System.Web.UI.WebControls.Label lblActivos;

        protected global::System.Web.UI.WebControls.Label lblConAlumnos;

        protected global::System.Web.UI.WebControls.Label lblSinUsuario;

        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;

        protected global::System.Web.UI.WebControls.TextBox txtBusqueda;

        protected global::System.Web.UI.HtmlControls.HtmlButton btnFiltrar;

        protected global::System.Web.UI.WebControls.GridView gvEntrenadores;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl footerText;

        protected global::System.Web.UI.HtmlControls.HtmlButton btnCrear;

        protected global::System.Web.UI.HtmlControls.HtmlButton btnModificar;

        protected global::System.Web.UI.HtmlControls.HtmlButton btnEliminar;

        protected global::System.Web.UI.HtmlControls.HtmlButton btnCancelar;

        protected global::System.Web.UI.WebControls.Panel pnlForm;

        protected global::System.Web.UI.WebControls.Label lblFormTitle;

        protected global::System.Web.UI.HtmlControls.HtmlButton btnCloseForm;

        protected global::System.Web.UI.WebControls.Panel pnlReadonlyNote;

        protected global::System.Web.UI.WebControls.TextBox txtDNI;

        protected global::System.Web.UI.WebControls.TextBox txtTelefono;

        protected global::System.Web.UI.WebControls.TextBox txtApellido;

        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        protected global::System.Web.UI.WebControls.TextBox txtFechaNacimiento;

        protected global::System.Web.UI.WebControls.CheckBox chkActivo;

        protected global::System.Web.UI.HtmlControls.HtmlButton btnGuardar;

        protected global::System.Web.UI.WebControls.Panel pnlConfirmarEliminar;

        protected global::System.Web.UI.HtmlControls.HtmlButton btnCloseConfirm;

        protected global::System.Web.UI.WebControls.Label lblEntrenadorAEliminar;

        protected global::System.Web.UI.WebControls.HiddenField hdnDniAEliminar;

        protected global::System.Web.UI.HtmlControls.HtmlButton btnCancelarEliminar;

        protected global::System.Web.UI.HtmlControls.HtmlButton btnConfirmarEliminar;
    }
}
