//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace gymAppV2.Alumnos
{


    public partial class Alumnos
    {

        /// <summary>
        /// badgeCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeCount;

        /// <summary>
        /// lblTotal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotal;

        /// <summary>
        /// lblActivos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblActivos;

        /// <summary>
        /// lblConRutinas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblConRutinas;

        /// <summary>
        /// lblSinUsuario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSinUsuario;

        /// <summary>
        /// ddlEstado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;

        /// <summary>
        /// ddlUsuario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlUsuario;

        /// <summary>
        /// txtBusqueda control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtBusqueda;

        /// <summary>
        /// btnFiltrar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnFiltrar;

        /// <summary>
        /// gvAlumnos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvAlumnos;

        /// <summary>
        /// footerText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl footerText;

        /// <summary>
        /// btnCrear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCrear;

        /// <summary>
        /// btnModificar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnModificar;

        /// <summary>
        /// btnEliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnEliminar;

        /// <summary>
        /// btnAsociarUsuario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAsociarUsuario;

        /// <summary>
        /// btnCancelar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCancelar;

        /// <summary>
        /// pnlForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlForm;

        /// <summary>
        /// lblFormTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblFormTitle;

        /// <summary>
        /// btnCloseForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCloseForm;

        /// <summary>
        /// txtDNI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDNI;

        /// <summary>
        /// txtTelefono control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;

        /// <summary>
        /// txtApellido control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtApellido;

        /// <summary>
        /// txtNombre control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>
        /// txtFechaNacimiento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFechaNacimiento;

        /// <summary>
        /// txtPeso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtPeso;

        /// <summary>
        /// chkActivo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkActivo;

        /// <summary>
        /// pnlFamiliares control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlFamiliares;

        /// <summary>
        /// litFamiliaresVacio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litFamiliaresVacio;

        /// <summary>
        /// rptFamiliares control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptFamiliares;

        /// <summary>
        /// btnGuardar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnGuardar;

        /// <summary>
        /// btnCancelarForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCancelarForm;

        /// <summary>
        /// btnContinuarAlta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnContinuarAlta;

        /// <summary>
        /// pnlConfirmarEliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlConfirmarEliminar;

        /// <summary>
        /// btnCloseConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCloseConfirm;

        /// <summary>
        /// lblAlumnoAEliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblAlumnoAEliminar;

        /// <summary>
        /// hdnDniAEliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnDniAEliminar;

        /// <summary>
        /// btnCancelarEliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCancelarEliminar;

        /// <summary>
        /// btnConfirmarEliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnConfirmarEliminar;

        /// <summary>
        /// pnlAsistente control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAsistente;

        /// <summary>
        /// lblAsistenteTitulo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAsistenteTitulo;

        /// <summary>
        /// btnAsistenteCerrar control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAsistenteCerrar;

        /// <summary>
        /// lblAsistenteMensaje control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAsistenteMensaje;

        /// <summary>
        /// pnlAsistentePreguntarTutor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAsistentePreguntarTutor;

        /// <summary>
        /// btnAsistenteTutorNo control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAsistenteTutorNo;

        /// <summary>
        /// btnAsistenteTutorSi control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAsistenteTutorSi;

        /// <summary>
        /// pnlAsistenteBuscarVinculo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAsistenteBuscarVinculo;

        /// <summary>
        /// txtAsistenteDniVinculo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAsistenteDniVinculo;

        /// <summary>
        /// ddlAsistenteParentesco control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlAsistenteParentesco;

        /// <summary>
        /// btnAsistenteBuscarVinculo control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAsistenteBuscarVinculo;

        /// <summary>
        /// pnlAsistenteConfirmarAlumno control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAsistenteConfirmarAlumno;

        /// <summary>
        /// btnAsistenteConfirmarAlumnoNo control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAsistenteConfirmarAlumnoNo;

        /// <summary>
        /// btnAsistenteConfirmarAlumnoSi control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAsistenteConfirmarAlumnoSi;

        /// <summary>
        /// pnlAsistenteConfirmarVinculo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAsistenteConfirmarVinculo;

        /// <summary>
        /// btnAsistenteConfirmarVinculoNo control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAsistenteConfirmarVinculoNo;

        /// <summary>
        /// btnAsistenteConfirmarVinculoSi control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAsistenteConfirmarVinculoSi;

        /// <summary>
        /// pnlAsistenteDatosVinculo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAsistenteDatosVinculo;

        /// <summary>
        /// txtAsistenteVinculoApellido control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAsistenteVinculoApellido;

        /// <summary>
        /// txtAsistenteVinculoNombre control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAsistenteVinculoNombre;

        /// <summary>
        /// txtAsistenteVinculoTelefono control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAsistenteVinculoTelefono;

        /// <summary>
        /// txtAsistenteVinculoEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAsistenteVinculoEmail;

        /// <summary>
        /// txtAsistenteVinculoFechaNac control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAsistenteVinculoFechaNac;

        /// <summary>
        /// pnlAsistenteCredenciales control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAsistenteCredenciales;

        /// <summary>
        /// txtAsistenteUsuarioSugerido control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAsistenteUsuarioSugerido;

        /// <summary>
        /// txtAsistenteContrasena control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAsistenteContrasena;

        /// <summary>
        /// btnAsistenteCrearAlumno control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAsistenteCrearAlumno;

        /// <summary>
        /// btnAsistenteCrearVinculo control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAsistenteCrearVinculo;

        /// <summary>
        /// pnlCredenciales control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlCredenciales;

        /// <summary>
        /// btnCerrarCredenciales control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCerrarCredenciales;

        /// <summary>
        /// litCredenciales control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCredenciales;

        /// <summary>
        /// btnCerrarCredenciales2 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCerrarCredenciales2;

        protected global::System.Web.UI.WebControls.Literal litTitulo;
        protected global::System.Web.UI.WebControls.Literal litStatTotal;
        protected global::System.Web.UI.WebControls.Literal litStatActivos;
        protected global::System.Web.UI.WebControls.Literal litStatConRutinas;
        protected global::System.Web.UI.WebControls.Literal litStatSinUsuario;
        protected global::System.Web.UI.WebControls.Literal litListaTitulo;
        protected global::System.Web.UI.WebControls.Literal litBtnCrear;
        protected global::System.Web.UI.WebControls.Literal litBtnModificar;
        protected global::System.Web.UI.WebControls.Literal litBtnEliminar;
        protected global::System.Web.UI.WebControls.Literal litBtnAsociar;
        protected global::System.Web.UI.WebControls.Literal litBtnCancelar;
        protected global::System.Web.UI.WebControls.Literal litBtnGuardar;
        protected global::System.Web.UI.WebControls.Literal litConfirmarTitulo;
        protected global::System.Web.UI.WebControls.Literal litConfirmarMsg;
        protected global::System.Web.UI.WebControls.Literal litConfirmarAviso;
        protected global::System.Web.UI.WebControls.Literal litBtnCancelarEliminar;
        protected global::System.Web.UI.WebControls.Literal litBtnConfirmarEliminar;
    }
}
