//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gymAppV2.Aulas
{


    public partial class Aulas
    {
        protected global::System.Web.UI.WebControls.Literal litTitulo;
        protected global::System.Web.UI.WebControls.Literal litSubtitulo;
        protected global::System.Web.UI.WebControls.LinkButton btnNuevaAula;
        protected global::System.Web.UI.WebControls.Literal litBtnNueva;
        protected global::System.Web.UI.WebControls.Repeater rptAulas;
        protected global::System.Web.UI.WebControls.PlaceHolder phSinAulas;
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        protected global::System.Web.UI.WebControls.Literal litFormTitulo;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.TextBox txtCupo;
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
