//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gymAppV2.Pagos
{


    public partial class PagosCliente
    {

        protected global::System.Web.UI.WebControls.Literal litTitulo;
        protected global::System.Web.UI.WebControls.Literal litSubtitulo;

        /// <summary>
        /// pnlCliente control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlCliente;

        protected global::System.Web.UI.WebControls.Literal litClienteMsg;
        protected global::System.Web.UI.WebControls.Literal litListaClienteTitulo;
        protected global::System.Web.UI.WebControls.GridView gvPagosCliente;

        /// <summary>
        /// pnlAdmin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAdmin;

        protected global::System.Web.UI.WebControls.Literal litListaTitulo;
        protected global::System.Web.UI.WebControls.GridView gvPagos;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl footerText;

        /// <summary>
        /// btnRegistrar control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnRegistrar;
        protected global::System.Web.UI.WebControls.Literal litBtnRegistrar;

        /// <summary>
        /// pnlForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;

        protected global::System.Web.UI.WebControls.Literal litFormTitulo;

        /// <summary>
        /// btnCloseForm control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCloseForm;

        protected global::System.Web.UI.WebControls.Literal litCampoAlumno;
        protected global::System.Web.UI.WebControls.DropDownList ddlAlumno;
        protected global::System.Web.UI.WebControls.Literal litCampoModalidad;
        protected global::System.Web.UI.WebControls.DropDownList ddlModalidad;
        protected global::System.Web.UI.WebControls.Literal litCampoPeriodo;
        protected global::System.Web.UI.WebControls.TextBox txtPeriodo;
        protected global::System.Web.UI.WebControls.Literal litCampoPeriodoHint;
        protected global::System.Web.UI.WebControls.Literal litCampoMetodo;
        protected global::System.Web.UI.WebControls.DropDownList ddlMetodoPago;
        protected global::System.Web.UI.WebControls.Literal litCampoMonto;
        protected global::System.Web.UI.WebControls.Label lblMontoPreview;

        /// <summary>
        /// btnGuardar control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnGuardar;

        /// <summary>
        /// btnCancelarForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCancelarForm;
        protected global::System.Web.UI.WebControls.Literal litBtnGuardar;
    }
}
