//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gymAppV2.VerificacioDV
{
    public partial class VerificacioDV
    {
        protected global::System.Web.UI.WebControls.Panel pnlNoAdmin;
        protected global::System.Web.UI.WebControls.Button btnLogoutBloqueo;

        protected global::System.Web.UI.WebControls.Panel pnlAdmin;
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl cardTotal;
        protected global::System.Web.UI.WebControls.Label lblTotalTablas;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl cardErrores;
        protected global::System.Web.UI.WebControls.Label lblTotalErrores;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl cardOk;
        protected global::System.Web.UI.WebControls.Label lblTablasOk;

        protected global::System.Web.UI.WebControls.Panel pnlInicializar;
        protected global::System.Web.UI.WebControls.Button btnInicializar;

        protected global::System.Web.UI.WebControls.Button btnVerificar;
        protected global::System.Web.UI.WebControls.Button btnRecalcular;
        protected global::System.Web.UI.WebControls.Button btnRestaurar;
        protected global::System.Web.UI.WebControls.Button btnSalir;

        protected global::System.Web.UI.WebControls.Panel pnlRestaurar;
        protected global::System.Web.UI.WebControls.TextBox txtRutaBackup;
        protected global::System.Web.UI.WebControls.Button btnConfirmarRestaurar;
        protected global::System.Web.UI.WebControls.Button btnCancelarRestaurar;

        protected global::System.Web.UI.WebControls.GridView gvEstadoControl;
        protected global::System.Web.UI.WebControls.GridView gvResultados;
    }
}
