//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gymAppV2.Admin
{


    public partial class BackupRestore
    {

        /// <summary>
        /// pnlBackup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlBackup;

        /// <summary>
        /// rblFormatoBackup control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButtonList rblFormatoBackup;

        /// <summary>
        /// lblRutaBackup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblRutaBackup;

        /// <summary>
        /// txtRutaBackup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtRutaBackup;

        /// <summary>
        /// btnGenerarNombre control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnGenerarNombre;

        /// <summary>
        /// btnRealizarBackup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnRealizarBackup;

        /// <summary>
        /// pnlRestore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlRestore;

        /// <summary>
        /// rblFormatoRestore control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButtonList rblFormatoRestore;

        protected global::System.Web.UI.WebControls.DropDownList ddlBackupsRestore;

        protected global::System.Web.UI.WebControls.Button btnActualizarListaRestore;

        /// <summary>
        /// lblRutaRestore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblRutaRestore;

        /// <summary>
        /// txtRutaRestore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtRutaRestore;

        /// <summary>
        /// btnRealizarRestore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnRealizarRestore;
    }
}
