//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gymAppV2.Permisos
{


    public partial class Permisos
    {
        protected global::System.Web.UI.WebControls.Literal litTitulo;
        protected global::System.Web.UI.WebControls.Literal litSubtitulo;
        protected global::System.Web.UI.WebControls.Panel pnlSinTabla;
        protected global::System.Web.UI.WebControls.Literal litSinTablaTitulo;
        protected global::System.Web.UI.WebControls.Literal litSinTablaMsg;
        protected global::System.Web.UI.WebControls.Panel pnlMatriz;
        protected global::System.Web.UI.WebControls.Literal litAyuda;
        protected global::System.Web.UI.WebControls.Literal litColPermiso;
        protected global::System.Web.UI.WebControls.Repeater rptPermisos;
        protected global::System.Web.UI.WebControls.Button btnRestablecer;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
